# Generated by Django 4.2 on 2022-12-23 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(default='', max_length=35)),
                ('day_text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(default='', max_length=35)),
                ('note_text', models.TextField(blank=True, default='')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 33, 30, 972798, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('day', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attached_notes', to='calendarApp.day')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(default='', max_length=35)),
                ('days', models.ManyToManyField(to='calendarApp.day')),
            ],
        ),
    ]
