# Generated by Django 4.2 on 2022-12-23 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='days',
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 35, 44, 207226, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
