# Generated by Django 4.2 on 2022-12-23 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0002_remove_month_days_month_year_alter_note_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 43, 46, 299431, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
