# Generated by Django 4.2 on 2022-12-23 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0003_alter_note_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day_text',
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='calendarApp.month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 46, 7, 454697, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
