# Generated by Django 4.2 on 2022-12-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0004_remove_day_day_text_day_month_alter_month_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 8, 46, 58, 464652, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
